### ISSUE TITLE
Support for Alfresco 5.0 and Community?

### ISSUE THREAD

**Issue by binduwavell** [jpotts/share-announcements#2]
I see on addons (https://addons.alfresco.com/addons/share-announcements) that only Alfresco Enterprise 5.1 is currently supported.

I was wondering if you plan to add support for Alfresco 5.0 and/or Community?

FWIW, I just installed on Alfresco 5.0.d and it installed OK. And the web script seemed to work, however the login page was not updated when I created an Announcement text file (although it did show up in the web script output.)

**Comment by binduwavell** [comment]
I missed the following configuration step from the README:

> At the present time, the bootstrapped folder does not grant "Guest" consumer access to the
> Announcements folder, so you'll have to do that manually, otherwise the announcements won't
> be returned to unauthenticated users.

I validated that with this step it's working with 5.1.1. I will now test with 5.1.e, 5.0.d and 5.0.1 and report back.

**Comment by binduwavell** [comment]
By performing that configuration step I was able to validate 5.1.e, 5.0.d and 5.0.1 all work. As such maybe we could change this issue simply to update the list of supported versions on the addons page?

**Comment by jpotts** [comment]
Okay, sounds good, thanks for testing those versions.

**Comment by KoichiNakata** [comment]
Great news!!　Your addon worked on my alfresco community 5.2.

**Comment by jpotts** [comment]
Cool, thanks for letting us know.

**Comment by jpotts** [comment]
I've updated the addons entry to indicate CE and EE 5.0 and 5.1.
